In [ ]:
%pip install kaggle
%pip install pandas

In [3]:
!kaggle datasets download -d lainguyn123/student-performance-factors

Dataset URL: https://www.kaggle.com/datasets/lainguyn123/student-performance-factors
License(s): CC0-1.0
Downloading student-performance-factors.zip to c:\Users\Ify\OneDrive\Documents\StudentPerformance_CluesBlues\Student-performance-Machine-Learning-Models

  0%|          | 0.00/93.9k [00:00<?, ?B/s]
100%|██████████| 93.9k/93.9k [00:00<00:00, 8.04MB/s]

In [4]:
import zipfile

with zipfile.ZipFile("student-performance-factors.zip", "r") as zip_ref:
    zip_ref.extractall("student_performance")

In [52]:
import pandas as pd

df = pd.read_csv("student_performance\StudentPerformanceFactors.csv")
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

Let's find the number of missing data from each column

In [53]:
missing_data = df.isnull().sum()
missing_data

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

Now let's find the percentage of missing data, so that we can confirm it's safe to adjust the data if there aren't too many missing values (more than 30%)

In [9]:
missing_percentage = (100 / df.shape[0]) * missing_data
missing_df = pd.DataFrame({ 
    'Missing Percent': missing_percentage
}, index=df.columns)

missing_df = missing_df[missing_df['Missing Percent'] > 0]

missing_df

                          Missing Percent
Teacher_Quality                  1.180566
Parental_Education_Level         1.362192
Distance_from_Home               1.014076

Now that we have the missing percentage, we now know it is fine to fill in the missing values as they don't take up an excess percentage. We'll fill in all missing values for the 3 features using their mode values.

In [25]:
#find the mode for each of the features needing adjustments
Teacher_Quality_mode = df.mode(dropna=True)["Teacher_Quality"][0]
Parental_Education_Level_mode = df.mode(dropna=True)["Parental_Education_Level"][0]
Distance_from_Home_mode = df.mode(dropna=True)["Distance_from_Home"][0]

print(f"The mode for Teacher Quality is: {Teacher_Quality_mode}\nThe mode for Parental Education is: {Parental_Education_Level_mode}\nthe mode for Distance from Home is: {Distance_from_Home_mode}")

The mode for Teacher Quality is: Medium
The mode for Parental Education is: High School
the mode for Distance from Home is: Near

In [60]:
#now fill in the missing values with the modes
df['Teacher_Quality'].fillna(Teacher_Quality_mode, inplace=True)
df['Parental_Education_Level'].fillna(Parental_Education_Level_mode, inplace=True)
df['Distance_from_Home'].fillna(Distance_from_Home_mode, inplace=True)

missing_data = df.isnull().sum()
missing_data

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64